services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - APP_URL=${APP_URL:-http://172.21.32.1:5173/}
      - HEADLESS=true
    volumes:
      - ./screenshots:/app/screenshots  # опционально: сохранять скриншоты
